### ISSUE TITLE
Delete resolved notes after some time

### ISSUE THREAD

**Issue by simon-lammes** [simon-lammes/lammes-assistant#44]
> As an admin, I want old resolved notes to be deleted on a regular basis so that the database doesn't store irrelevant data.

### Tasks

- [ ] Create admin route
- [ ] Create variable `defaultRestoreTimeframe`. This is a part of the application configuration that specifies how long the user has time to restore a removed entity before it is permanently deleted.
- [ ] create mutation 'pruneNotes' (inspired by the command `docker container prune`)

### Scope

- For simplicity, everyone is an admin for now 😉
